# Uncomment the next line to define a global platform for your project
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'

target 'ironPitch' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  	pod 'AFNetworking', '~> 3.0'
  # Pods for ironPitch

  target 'ironPitchTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ironPitchUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
