# Uncomment the next line to define a global platform for your project
# platform :ios, '11.0'

target 'AppStore iOS 10' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AppStore iOS 10
  pod "LBTAComponents"
  pod "EXTView"
  pod 'SimpleImageViewer', '~> 1.0.2'
  pod 'Alamofire', '~> 4.4'
  pod 'Kingfisher', '~> 3.0'
  pod 'Cosmos', '~> 10.0'
  pod 'ReadMoreTextView', '~> 2.0.0'
  pod 'AZSearchView'
  pod 'PFWebViewController', '~> 1.1.1'
  pod 'BMPlayer', '~> 0.9.1'
end

target 'ironPitch' do
    # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
    use_frameworks!
    
    # Pods for AppStore iOS 10
    pod "LBTAComponents"
    pod "EXTView"
    pod 'SimpleImageViewer', '~> 1.0.2'
    pod 'Alamofire', '~> 4.4'
    pod 'Kingfisher', '~> 3.0'
    pod 'Cosmos', '~> 10.0'
    pod 'ReadMoreTextView', '~> 2.0.0'
    pod 'AZSearchView'
    pod 'PFWebViewController', '~> 1.1.1'
    pod 'BMPlayer', '~> 0.9.1'
end
